name: what

on: # 실행 조건 설정
  push:
    branches:
      - "staging/**" # 와일드카드 패턴

jobs: # 작업 내용 명시
  what:
    name: Install and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check lint
        run: npm run lint
  native:
    name: native
    runs-on: ubuntu-latest
    env:
      working-directory: app/native

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build
        run: eas build --platform all --profile preview
        working-directory: ${{ env.working-directory }}

      # - name: Submit
      #   run: eas submit --platform all --profile preview
      #   working-directory: ${{ env.working-directory }}
